### PR TITLE
indicate the current migration

### PR DESCRIPTION
**Pull request by XavCC**
+ from github => framagit
+ Still in trouble, I Have to fix it, ~~[ISSUE](https://framagit.org/Xavcc/formations/issues/1)~~

### CODE REVIEW

**Comment by Yehonal** [comment]
you should link here your wiki page not repository, please

**Comment by XavCC** [comment]
I working on it, and will link it as you wish when it will work, with a short "how to fork in gitlab/framagit and stay linked with git-wiki roots" obviously. 

BTW, any ideas why in gitlab/framagit the landing page browse and return a authentication request (web visitors) or error 404 (for gitlab/famagit logged in) ?

Thx !

**Comment by Yehonal** [comment]
Gitwiki does't support gitlab for now, i should change various internal features to make it works but it's not in roadmap at the moment.
Please use github pages instead

**Comment by Yehonal** [comment]
hi @XavCC , i've started an experimental repository for gitlab: https://gitlab.com/drassil/git-wiki

it's working but i've to test deeply and allow the "master" to interop with both gitlab and github

currently there's a gl-pages branch that's the only one configured for gitlab, where i'm developing on

**Comment by XavCC** [comment]
I Will try to use it

Then, send you feedbacks

And _in fine_ add it in this PR

Do you agree with this flow ?

**Comment by Yehonal** [comment]
i've fixed some bugs on gitlab, now it should 100% usable.

Let me know and i'll update it

**Comment by Yehonal** [comment]
close for inactivity

**Pull request closed without merging**
